export const GET_CARTS = 'GET_CARTS'
export const SAVE_CARTS = 'SAVE_CARTS'
export const DELETE_CART = 'DELETE_CART'
export const ADD_CART = 'ADD_CART'

export const TOGGLE_AUTH = 'TOGGLE_AUTH'

export const PRODUCT_LOADED_SUCCESS = 'PRODUCT_LOADED_SUCCESS'
export const PRODUCT_LOADED_FAIL = 'PRODUCT_LOADED_FAIL'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const FIND_PRODUCT = 'FIND_PRODUCT'
export const PRODUCT_FILTER = 'PRODUCT_FILTER'