export const TOGGLE_AUTH = 'TOGGLE_AUTH'

export const PRODUCT_LOADED_SUCCESS = 'PRODUCT_LOADED_SUCCESS'
export const PRODUCT_LOADED_FAIL = 'PRODUCT_LOADED_FAIL'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const FIND_PRODUCT = 'FIND_PRODUCT'
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL'
export const PRODUCT_FILTER_CATEGORY = 'PRODUCT_FILTER_CATEGORY'
export const PRODUCT_SORT = 'PRODUCT_SORT'
export const PRODUCT_SEARCH = 'PRODUCT_SEARCH'
// export const PRODUCT_D = 'PRODUCT_SEARCH'


export const GET_CARTS = 'GET_CARTS'
export const ADD_CART = 'ADD_CART'
export const SAVE_CARTS = 'SAVE_CARTS'
export const DELETE_CART = 'DELETE_CART'

export const USER_LOGIN = 'USER_LOGIN'
// export const ADD_CART = 'ADD_CART'
// export const SAVE_CARTS = 'SAVE_CARTS'
// export const DELETE_CART = 'DELETE_CART'